title: Kelvin van Hoorn
description: Kelvin van Hoorn's personal website

theme: null

markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- README.md 