title: Kelvin van Hoorn
description: Kelvin van Hoorn's website for technical art
author: Kelvin van Hoorn
image: /assets/favicon/favicon.png

twitter:
  username: kelvinvanhoorn
  card: summary

permalink: /:year/:month/:day/:title/

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed

# highlighter: rouge

exclude:
- "*.gemspec"
- LICENSE.md
- README.md 