title: Kelvin van Hoorn
tagline: Kelvin van Hoorn's personal website
description: Kelvin van Hoorn's personal website
author: Kelvin van Hoorn

twitter:
  username: kelvinvanhoorn
  card: summary

permalink: /:year/:month/:day/:title:output_ext

google_analytics: G-8P9Z3T84Q4
# google_analytics: G-4ERF4SWF6C

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed

highlighter: rouge

exclude:
- "*.gemspec"
- LICENSE.md
- README.md 